name: Android-APK-Build

on:
  workflow_dispatch:
    # Allows manually triggering this workflow from the Actions tab

jobs:
  build-android:
    name: 🎉 Android Build
    runs-on: ubuntu-latest
    # Uses the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v3
        # Checks out your repository to the GitHub Actions runner

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        # Sets up Flutter SDK, ensuring it's the stable channel

      - run: flutter pub get
        # Installs the Dart and Flutter dependencies specified in pubspec.yaml

      - run: flutter build apk --release
        # Builds the APK file in release mode

      - name: Zip output
        run: zip -qq -r -9 AnimeBerSerk.apk build/app/outputs/flutter-apk/app-release.apk
        # Zips the APK file for easy download

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          tag: v1.0
          overwrite: true
          body: "This is first release"
        # Uploads the APK file to the GitHub Releases page
